export const countryCodes = [
  { code: "+20", country: "Egypt (مصر)", iso: "EG" },
  { code: "+966", country: "Saudi Arabia (السعودية)", iso: "SA" },
  { code: "+971", country: "UAE (الإمارات)", iso: "AE" },
  { code: "+965", country: "Kuwait (الكويت)", iso: "KW" },
  { code: "+974", country: "Qatar (قطر)", iso: "QA" },
  { code: "+973", country: "Bahrain (البحرين)", iso: "BH" },
  { code: "+968", country: "Oman (عُمان)", iso: "OM" },
  { code: "+962", country: "Jordan (الأردن)", iso: "JO" },
  { code: "+961", country: "Lebanon (لبنان)", iso: "LB" },
  { code: "+964", country: "Iraq (العراق)", iso: "IQ" },
  { code: "+970", country: "Palestine (فلسطين)", iso: "PS" },
  { code: "+963", country: "Syria (سوريا)", iso: "SY" },
  { code: "+967", country: "Yemen (اليمن)", iso: "YE" },
  { code: "+218", country: "Libya (ليبيا)", iso: "LY" },
  { code: "+249", country: "Sudan (السودان)", iso: "SD" },
  { code: "+212", country: "Morocco (المغرب)", iso: "MA" },
  { code: "+213", country: "Algeria (الجزائر)", iso: "DZ" },
  { code: "+216", country: "Tunisia (تونس)", iso: "TN" },
  { code: "+222", country: "Mauritania (موريتانيا)", iso: "MR" },
  { code: "+252", country: "Somalia (الصومال)", iso: "SO" },
  { code: "+1", country: "United States / Canada", iso: "US" },
  { code: "+44", country: "United Kingdom", iso: "GB" },
  { code: "+49", country: "Germany", iso: "DE" },
  { code: "+33", country: "France", iso: "FR" },
  { code: "+39", country: "Italy", iso: "IT" },
  { code: "+34", country: "Spain", iso: "ES" },
  { code: "+90", country: "Turkey (تركيا)", iso: "TR" },
  { code: "+98", country: "Iran (إيران)", iso: "IR" },
  { code: "+92", country: "Pakistan (باكستان)", iso: "PK" },
  { code: "+91", country: "India (الهند)", iso: "IN" },
  { code: "+86", country: "China", iso: "CN" },
  { code: "+81", country: "Japan", iso: "JP" },
  { code: "+61", country: "Australia", iso: "AU" },
  { code: "+7", country: "Russia", iso: "RU" },
  { code: "+55", country: "Brazil", iso: "BR" }
];
