-- LTD System Migration
-- Creates the required tables and logic for Lifetime Deals (LTDs).

-- 1. ltd_codes
-- Stores the actual codes generated by the Super Admin
CREATE TABLE public.ltd_codes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code TEXT UNIQUE NOT NULL,
    tier_id TEXT NOT NULL CHECK (tier_id IN ('starter', 'pro', 'business', 'enterprise')),
    max_redemptions INTEGER NOT NULL DEFAULT 1,
    current_redemptions INTEGER NOT NULL DEFAULT 0,
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. company_entitlements
-- Stores the permanent entitlement granted to the company (tenant)
CREATE TABLE public.company_entitlements (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    tier_id TEXT NOT NULL,
    type TEXT DEFAULT 'ltd' CHECK (type = 'ltd'),
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
    source TEXT DEFAULT 'code' CHECK (source IN ('code', 'admin', 'marketplace')),
    reference_id TEXT, -- The LTD code string that was redeemed
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, type) -- Ensure max 1 active LTD type per company
);

-- 3. entitlement_logs
-- Immutable audit log for support and security tracing
CREATE TABLE public.entitlement_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
    action TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- RLS for ltd_codes (Only God mode admin can read/write directly, others use RPC or edge functions via service role)
ALTER TABLE public.ltd_codes ENABLE ROW LEVEL SECURITY;
-- No public policies, use service role.

-- RLS for company_entitlements
ALTER TABLE public.company_entitlements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Owners can view their own entitlements" ON public.company_entitlements
    FOR SELECT USING (
        company_id IN (SELECT id FROM public.companies WHERE owner_id = auth.uid())
    );

-- RLS for entitlement_logs
ALTER TABLE public.entitlement_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Owners can view their own entitlement logs" ON public.entitlement_logs
    FOR SELECT USING (
        company_id IN (SELECT id FROM public.companies WHERE owner_id = auth.uid())
    );

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_ltd_codes_code ON public.ltd_codes(code);
CREATE INDEX IF NOT EXISTS idx_company_entitlements_lookup ON public.company_entitlements(company_id, status);

-- Add RPC function to safely redeem a code natively in Postgres to prevent race conditions
CREATE OR REPLACE FUNCTION public.redeem_ltd_code(p_code TEXT, p_company_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_ltd_record RECORD;
    v_existing_entitlement RECORD;
BEGIN
    -- 1. Lock the code row FOR UPDATE to prevent concurrent redemption of the same slot
    SELECT * INTO v_ltd_record 
    FROM public.ltd_codes 
    WHERE code = p_code
    FOR UPDATE;

    IF NOT FOUND THEN
        RETURN jsonb_build_object('success', false, 'error', 'Code not found');
    END IF;

    -- 2. Validations
    IF NOT v_ltd_record.is_active THEN
        RETURN jsonb_build_object('success', false, 'error', 'Code is inactive');
    END IF;

    IF v_ltd_record.expires_at IS NOT NULL AND v_ltd_record.expires_at < NOW() THEN
        RETURN jsonb_build_object('success', false, 'error', 'Code has expired');
    END IF;

    IF v_ltd_record.current_redemptions >= v_ltd_record.max_redemptions THEN
        RETURN jsonb_build_object('success', false, 'error', 'Code redemption limit reached');
    END IF;

    -- 3. Idempotency Check
    SELECT * INTO v_existing_entitlement 
    FROM public.company_entitlements 
    WHERE company_id = p_company_id AND type = 'ltd';

    IF FOUND THEN
        IF v_existing_entitlement.reference_id = p_code THEN
            RETURN jsonb_build_object('success', true, 'message', 'Code already redeemed by you', 'tier', v_existing_entitlement.tier_id);
        ELSE
            -- Upgrade or replace existing LTD
            UPDATE public.company_entitlements
            SET tier_id = v_ltd_record.tier_id,
                reference_id = p_code,
                source = 'code',
                status = 'active',
                created_at = NOW()
            WHERE id = v_existing_entitlement.id;

            -- Log
            INSERT INTO public.entitlement_logs (company_id, action, metadata)
            VALUES (p_company_id, 'ltd_upgraded', jsonb_build_object('old_tier', v_existing_entitlement.tier_id, 'new_tier', v_ltd_record.tier_id, 'code', p_code));
        END IF;
    ELSE
        -- Insert new entitlement
        INSERT INTO public.company_entitlements (company_id, tier_id, type, source, reference_id)
        VALUES (p_company_id, v_ltd_record.tier_id, 'ltd', 'code', p_code);

        -- Log
        INSERT INTO public.entitlement_logs (company_id, action, metadata)
        VALUES (p_company_id, 'ltd_redeemed', jsonb_build_object('tier', v_ltd_record.tier_id, 'code', p_code));
    END IF;

    -- 4. Increment redemption count safely
    UPDATE public.ltd_codes
    SET current_redemptions = current_redemptions + 1
    WHERE id = v_ltd_record.id;

    RETURN jsonb_build_object('success', true, 'message', 'Code successfully redeemed', 'tier', v_ltd_record.tier_id);

EXCEPTION WHEN OTHERS THEN
    RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;
